sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kjadhavaws/jwcw-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kjadhavaws/jwcw-docker-react npm run test
